version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest-microservices
    expose:
      - "3001"
      - "3002"
      - "3003"
      - "3004"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - app
    ports:
      - "8080:80"  # Host port : Container port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
